build:
  stage: build

  before_script:
    - apt update && apt -y install devscripts git-buildpackage
    - mk-build-deps --tool "apt -y -o Debug::pkgProblemResolver=yes --no-install-recommends" --install -r debian/control

  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - gbp buildpackage -uc -us --git-ignore-branch
    - mkdir build
    - mv ../*.udeb build/

  artifacts:
    paths:
      - build/*
